export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = 'LOGOUT_USER'


export const SET_UPDATE_USER = 'SET_UPDATE_USER'
export const EDIT_USER_BEGIN= 'EDIT_USER_BEGIN'
export const EDIT_USER_SUCCESS= 'EDIT_USER_SUCCESS'
export const EDIT_USER_ERROR= 'EDIT_USER_ERROR'
export const TOGGLE_ADMIN = 'TOGGLE_ADMIN'

export const DELETE_USER_BEGIN = 'DELETE_USER_BEGIN'

export const UPDATE_PROFILE_BEGIN = 'UPDATE_PROFILE_BEGIN'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_EVENT_BEGIN = 'CREATE_EVENT_BEGIN'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_ERROR = 'CREATE_EVENT_ERROR'

export const GET_EVENT_BEGIN = 'GET_EVENT_BEGIN'
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS'

export const SET_EDIT_EVENT = 'SET_EDIT_EVENT'
export const EDIT_EVENT_BEGIN = 'EDIT_EVENT_BEGIN'
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS'
export const EDIT_EVENT_ERROR = 'EDIT_EVENT_ERROR'

export const EDIT_STATUS_BEGIN = 'EDIT_STATUS_BEGIN'
export const EDIT_STATUS_SUCCESS = 'EDIT_STATUS_SUCCESS'
export const EDIT_STATUS_ERROR = 'EDIT_STATUS_ERROR'
export const SET_SEARCH_STATUS = 'SET_SEARCH_STATUS'

export const DELETE_EVENT_BEGIN = 'DELETE_EVENT_BEGIN'

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const CHANGE_PAGE = 'CHANGE_PAGE'

export const GET_USER_BEGIN = 'GET_USER_BEGIN'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'

export const GET_USERS_BEGIN = 'GET_USERS_BEGIN'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'